// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7KFjL-YSF-faJ7oypwb8Y8cJkA9xNTng',
    appId: '1:423296603409:android:28acadf5bafe1998f828b0',
    messagingSenderId: '423296603409',
    projectId: 'casa-rancha',
    storageBucket: 'casa-rancha.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ59xbsTgfDgdoK9cy1cGz--aL1266i-I',
    appId: '1:423296603409:ios:51bc8fa4bdbdfab6f828b0',
    messagingSenderId: '423296603409',
    projectId: 'casa-rancha',
    storageBucket: 'casa-rancha.appspot.com',
    androidClientId: '423296603409-5hh1l47r8fadcvehk6p5jk7knn2d2k6n.apps.googleusercontent.com',
    iosClientId: '423296603409-6uvc04rt06buro6i4488i6ta85n8nnr7.apps.googleusercontent.com',
    iosBundleId: 'com.zb.casarancha',
  );
}
